src/Entity/ParentPereMere.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ParentPereMereRepository")
 */
class ParentPereMere
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_p1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom_p1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email_p1;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Sexe", inversedBy="parentP1")
     */
    private $sexe_p1;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $telephone_p1;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Civilite", inversedBy="civilte_p1")
     */
    private $civilite;

//    /**
//     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="parent_1", cascade={"persist", "remove"})
//     * @ORM\JoinColumn(nullable=false)
//     */
//    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name_p2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom_p2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email_p2;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Sexe", inversedBy="parent_p2")
     */
    private $sexe_p2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone_p2;

//    /**
//     * @ORM\OneToOne(targetEntity="App\Entity\Adresse", inversedBy="adresse_p2", cascade={"persist", "remove"})
//     */
//    private $adresse_p2;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Civilite", inversedBy="parent_p2")
     */
    private $civilite_p2;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SituationFamilialle", inversedBy="parentPereMeres")
     */
    private $situation_Familiale;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Adresse", mappedBy="adresse_p1", cascade={"persist", "remove"})
     */
    private $adresse_p1;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Eleve", mappedBy="parent_p1_p2", cascade={"persist", "remove"})
     */
    private $eleves;

    public function __construct()
    {
        $this->adresse_p1 = new ArrayCollection();
        $this->eleves = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameP1(): ?string
    {
        return $this->name_p1;
    }

    public function setNameP1(string $name_p1): self
    {
        $this->name_p1 = $name_p1;

        return $this;
    }

    public function getPrenomP1(): ?string
    {
        return $this->prenom_p1;
    }

    public function setPrenomP1(?string $prenom_p1): self
    {
        $this->prenom_p1 = $prenom_p1;

        return $this;
    }

    public function getEmailP1(): ?string
    {
        return $this->email_p1;
    }

    public function setEmailP1(?string $email_p1): self
    {
        $this->email_p1 = $email_p1;

        return $this;
    }

    public function getSexeP1(): ?Sexe
    {
        return $this->sexe_p1;
    }

    public function setSexeP1(?Sexe $sexe_p1): self
    {
        $this->sexe_p1 = $sexe_p1;

        return $this;
    }

    public function getTelephoneP1(): ?string
    {
        return $this->telephone_p1;
    }

    public function setTelephoneP1(?string $telephone_p1): self
    {
        $this->telephone_p1 = $telephone_p1;

        return $this;
    }

    /**
     * @return Collection|Adresse[]
     */
    public function getAdresseP1(): Collection
    {
        return $this->adresse_p1;
    }

    public function addAdresseP1(Adresse $adresseP1): self
    {
        if (!$this->adresse_p1->contains($adresseP1)) {
            $this->adresse_p1[] = $adresseP1;
            $adresseP1->setAdresseP1($this);
        }

        return $this;
    }

    public function removeAdresseP1(Adresse $adresseP1): self
    {
        if ($this->adresse_p1->contains($adresseP1)) {
            $this->adresse_p1->removeElement($adresseP1);
            // set the owning side to null (unless already changed)
            if ($adresseP1->getAdresseP1() === $this) {
                $adresseP1->setAdresseP1(null);
            }
        }

        return $this;
    }

    public function getCivilite(): ?Civilite
    {
        return $this->civilite;
    }

    public function setCivilite(?Civilite $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

//    public function getUser(): ?User
//    {
//        return $this->user;
//    }
//
//    public function setUser(User $user): self
//    {
//        $this->user = $user;
//
//        return $this;
//    }

    public function getNameP2(): ?string
    {
        return $this->name_p2;
    }

    public function setNameP2(?string $name_p2): self
    {
        $this->name_p2 = $name_p2;

        return $this;
    }

    public function getPrenomP2(): ?string
    {
        return $this->prenom_p2;
    }

    public function setPrenomP2(?string $prenom_p2): self
    {
        $this->prenom_p2 = $prenom_p2;

        return $this;
    }

    public function getEmailP2(): ?string
    {
        return $this->email_p2;
    }

    public function setEmailP2(?string $email_p2): self
    {
        $this->email_p2 = $email_p2;

        return $this;
    }

    public function getSexeP2(): ?Sexe
    {
        return $this->sexe_p2;
    }

    public function setSexeP2(?Sexe $sexe_p2): self
    {
        $this->sexe_p2 = $sexe_p2;

        return $this;
    }

    public function getTelephoneP2(): ?string
    {
        return $this->telephone_p2;
    }

    public function setTelephoneP2(?string $telephone_p2): self
    {
        $this->telephone_p2 = $telephone_p2;

        return $this;
    }

    public function getAdresseP2(): ?Adresse
    {
        return $this->adresse_p2;
    }

    public function setAdresseP2(?Adresse $adresse_p2): self
    {
        $this->adresse_p2 = $adresse_p2;

        return $this;
    }

    public function getCiviliteP2(): ?Civilite
    {
        return $this->civilite_p2;
    }

    public function setCiviliteP2(?Civilite $civilite_p2): self
    {
        $this->civilite_p2 = $civilite_p2;

        return $this;
    }

    public function getSituationFamiliale(): ?SituationFamilialle
    {
        return $this->situation_Familiale;
    }

    public function setSituationFamiliale(?SituationFamilialle $situation_Familiale): self
    {
        $this->situation_Familiale = $situation_Familiale;

        return $this;
    }

    /**
     * @return Collection|Eleve[]
     */
    public function getEleves(): Collection
    {
        return $this->eleves;
    }

    public function addEleve(Eleve $elefe): self
    {
        if (!$this->eleves->contains($elefe)) {
//            $this->eleves[] = $elefe;
            $this->eleves->add($elefe) ;
            $elefe->setParentP1P2($this);
        }

        return $this;
    }

    public function removeEleve(Eleve $elefe): self
    {
        if ($this->eleves->contains($elefe)) {
            $this->eleves->removeElement($elefe);
            // set the owning side to null (unless already changed)
//            if ($elefe->getParentP1P2() === $this) {
//                $elefe->setParentP1P2(null);
//            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNameP1().' '.$this->getPrenomP1().' - '.$this->getNameP2().' '.$this->getPrenomP2();
    }
}

src/Form/ParentPereMereType.php
<?php

namespace App\Form;

use App\Entity\Eleve;
use App\Entity\ParentPereMere;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParentPereMereType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_p1')
            ->add('prenom_p1')
            ->add('email_p1')
            ->add('telephone_p1')
            ->add('name_p2')
            ->add('prenom_p2')
            ->add('email_p2')
            ->add('telephone_p2')
            ->add('sexe_p1')
            ->add('civilite')
//            ->add('user')
            ->add('sexe_p2')
            ->add('adresse_p1', CollectionType::class, [
                'entry_type' => AdresseType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true
            ])
            ->add('civilite_p2')
            ->add('situation_Familiale')
//            ->add('eleves', EntityType::class, [
//                    'class' => Eleve::class
//            ])
             ->add('eleves', CollectionType::class, [
                'entry_type' => EleveType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true
            ])
            ->add('save', SubmitType::class)
        ;


    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ParentPereMere::class,
        ]);
    }
}

src/Controller/ParentPereMereController.php
<?php

namespace App\Controller;

use App\Entity\Adresse;
use App\Entity\Eleve;
use App\Entity\ParentPereMere;
use App\Form\ParentPereMereType;
use App\Repository\ParentPereMereRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @Route("/parent_peremere")
 */
class ParentPereMereController extends AbstractController
{
    /**
     * @Route("/", name="parent_pere_mere_index", methods={"GET"})
     */
    public function index(ParentPereMereRepository $parentPereMereRepository): Response
    {
        return $this->render('parent_pere_mere/index.html.twig', [
            'parent_pere_meres' => $parentPereMereRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="parent_pere_mere_new", methods={"GET","POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $parentPereMere = new ParentPereMere();
        $elev = new Eleve();
        $originalEleves = new ArrayCollection();

        $adresse = new Adresse();
        $parentPereMere->addAdresseP1($adresse);

        // Create an ArrayCollection of the current Tag objects in the database
        foreach ($parentPereMere->getEleves() as $eleve) {
            $originalEleves->add($eleve);
        }
        $form = $this->createForm(ParentPereMereType::class, $parentPereMere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
//            $entityManager = $this->getDoctrine()->getManager();
            foreach ($originalEleves as $eleve) {
                if (false === $parentPereMere->getEleves()->contains($eleve)) {
                    // remove the Task from the Tag
                    if (false === $parentPereMere->getEleves()->contains($eleve)) {
                    $parentPereMere->getEleves()->removeElement($parentPereMere);

                    // if it was a many-to-one relationship, remove the relationship like this
                    // $tag->setTask(null);

                    $entityManager->persist($eleve);

                    // if you wanted to delete the Tag entirely, you can also do that
                    // $entityManager->remove($tag);
                    }
                }
            }

            $entityManager->persist($parentPereMere);
            $entityManager->flush();

            return $this->redirectToRoute('parent_pere_mere_index');
        }

        return $this->render('parent_pere_mere/new.html.twig', [
            'parent_pere_mere' => $parentPereMere,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="parent_pere_mere_show", methods={"GET"})
     */
    public function show(ParentPereMere $parentPereMere): Response
    {
        return $this->render('parent_pere_mere/show.html.twig', [
            'parent_pere_mere' => $parentPereMere,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="parent_pere_mere_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, ParentPereMere $parentPereMere, EntityManagerInterface $entityManager): Response
    {
//        $form = $this->createForm(ParentPereMereType::class, $parentPereMere);
//        $form->handleRequest($request);

        if (null === $parentPereMere) {
            throw $this->createNotFoundException('No task found for id '.$request->get('id'));
        }
        $originalEleves = new ArrayCollection();
        $adresse = new Adresse();

        $parentPereMere->addAdresseP1($adresse);
        // Create an ArrayCollection of the current Tag objects in the database
        foreach ($parentPereMere->getEleves() as $eleve) {
            $originalEleves->add($eleve);
        }

        $editForm = $this->createForm(ParentPereMereType::class, $parentPereMere);

        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            // remove the relationship between the tag and the Task
            foreach ($originalEleves as $eleve) {
                if (false === $parentPereMere->getEleves()->contains($eleve)) {
                    // remove the Task from the Tag
                    $entityManager->remove($eleve);
//                    $parentPereMere->getEleves()->removeElement($eleve);

                    // if it was a many-to-one relationship, remove the relationship like this
                    // $tag->setTask(null);

//                    $entityManager->persist($eleve);

                    // if you wanted to delete the Tag entirely, you can also do that
                    // $entityManager->remove($tag);
                }
            }
            $entityManager->persist($parentPereMere);
            $entityManager->flush();
            return $this->redirectToRoute('parent_pere_mere_index');
        }



//        if ($form->isSubmitted() && $form->isValid()) {
//            $this->getDoctrine()->getManager()->flush();
//
//            return $this->redirectToRoute('parent_pere_mere_index');
//        }

        return $this->render('parent_pere_mere/edit.html.twig', [
            'parent_pere_mere' => $parentPereMere,
            'form' => $editForm->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="parent_pere_mere_delete", methods={"DELETE"})
     */
    public function delete(Request $request, ParentPereMere $parentPereMere): Response
    {
        if ($this->isCsrfTokenValid('delete'.$parentPereMere->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($parentPereMere);
            $entityManager->flush();
        }

        return $this->redirectToRoute('parent_pere_mere_index');
    }
}

templates/parent_pere_mere/_delete_form.html.twig
<form method="post" action="{{ path('parent_pere_mere_delete', {'id': parent_pere_mere.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ parent_pere_mere.id) }}">
    <button class="btn"  class="btn btn-danger">Delete</button>
</form>

templates/parent_pere_mere/_form.html.twig
{{ form_start(form) }}

{% macro mylookForm(eleve) %}
    <div class="row">
        <div class="col-md-3">
            {{ form_row(eleve.name) }}
        </div>
        <div class="col-md-3">
            {{ form_row(eleve.prenom) }}
        </div>
        <div class="col-md-5">
            {{ form_row(eleve.dateNaissance) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            {{ form_row(eleve.sexe) }}
        </div>
        <div class="col-md-3">
            {{ form_row(eleve.classeroom) }}
        </div>
    </div>
{% endmacro mylookForm %}
{%  import _self as formMacros %}


<div class="alert alert-danger" role="alert">
    {{ form_errors(form) }}
</div>

<div class="">
    <div class="row bd-callout bd-callout-warning">
        <div class="col-md-2">
            {{ form_row(form.civilite) }}
        </div>
        <div class="col-md-3">
            {{ form_row(form.name_p1) }}
        </div>
        <div class="col-md-3">
            {{ form_row(form.prenom_p1) }}
        </div>
        <div class="col-md-2">
            {{ form_row(form.situation_Familiale) }}
        </div>
        </div>
    <div class="row bd-callout bd-callout-warning">
        <div class="col-md-5">
             {{ form_row(form.email_p1) }}
        </div>
        <div class="col-md-3">
             {{ form_row(form.telephone_p1) }}
        </div>
        <div class="col-md-2">
             {{ form_row(form.sexe_p1) }}
        </div>
    </div>

    <div class="row bd-callout bd-callout-warning">
        <div class="col-md-2">
            {{ form_row(form.civilite_p2) }}
        </div>
        <div class="col-md-3">
            {{ form_row(form.name_p2) }}
        </div>
        <div class="col-md-3">
            {{ form_row(form.prenom_p2) }}
        </div>
    </div>
    <div class="row bd-callout bd-callout-warning">
        <div class="col-md-5">
             {{ form_row(form.email_p2) }}
        </div>
        <div class="col-md-3">
             {{ form_row(form.telephone_p2) }}
        </div>
        <div class="col-md-2">
            {{ form_row(form.sexe_p2) }}
        </div>
    </div>

    <div class="row bd-callout bd-callout-warning">
        {% for adr in form.adresse_p1 %}
           {% if adr is not null and adr is not empty %}
        <div class="col-md-2">
             {{ form_row(adr.numero) }}
         </div>
        <div class="col-md-4">
            {{ form_row(adr.adresse)}}
        </div>
        <div class="col-md-2">
            {{ form_row(adr.cp) }}
        </div>
        <div class="col-md-3">
            {{ form_row(adr.ville) }}
        </div>
            {% endif %}
        {% endfor %}

{#        <div class="col-md-2">#}
{#             {{ form_row(form.adresse_p1.numero) }}#}
{#        </div>#}
{#        <div class="col-md-3">#}
{#             {{ form_row(form.adresse_p1.adresse) }}#}
{#        </div>#}
{#        <div class="col-md-2">#}
{#            {{ form_row(form.adresse_p1.cp) }}#}
{#        </div>#}
{#        <div class="col-md-2">#}
{#            {{ form_row(form.adresse_p1.ville) }}#}
{#        </div>#}

    </div>

    <div class="col-sm-12 border-2" id="eleves_list" data-prototype="{{ formMacros.myLookForm(form.eleves.vars.prototype)|e('html_attr')}}" >
        <h3>Eleves</h3>
            {% for eleve in form.eleves %}
        <div class="panel panel-warning border border-primary ml-4 p-3 rounded">
            <div class="panel-heading">
            Eléve (enfant): {{ loop.index }}
            </div>
            <div class="panel-body">
                {{ formMacros.myLookForm(eleve) }}

            </div>

        </div>
            {% endfor %}


    </div>

</div>

{{ form_rest(form) }}
{#    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>#}
{{ form_end(form) }}

templates/parent_pere_mere/_form_new.html.twig
{{ form_start(form) }}
{#    {{ form_widget(form) }}#}
<div class="alert alert-danger" role="alert">
    {{ form_errors(form) }}
</div>

<div class="">
    <div class="row bd-callout bd-callout-warning">
        <div class="col-md-2">
            {{ form_row(form.civilite) }}
        </div>
        <div class="col-md-3">
            {{ form_row(form.name_p1) }}
        </div>
        <div class="col-md-3">
            {{ form_row(form.prenom_p1) }}
        </div>
        </div>
    <div class="row bd-callout bd-callout-warning">
        <div class="col-md-5">
             {{ form_row(form.email_p1) }}
        </div>
        <div class="col-md-3">
             {{ form_row(form.telephone_p1) }}
        </div>
        <div class="col-md-2">
             {{ form_row(form.sexe_p1) }}
        </div>
    </div>

    <div class="row bd-callout bd-callout-warning">
        <div class="col-md-2">
            {{ form_row(form.civilite_p2) }}
        </div>
        <div class="col-md-3">
            {{ form_row(form.name_p2) }}
        </div>
        <div class="col-md-3">
            {{ form_row(form.prenom_p2) }}
        </div>
    </div>
    <div class="row bd-callout bd-callout-warning">
        <div class="col-md-5">
             {{ form_row(form.email_p2) }}
        </div>
        <div class="col-md-3">
             {{ form_row(form.telephone_p2) }}
        </div>
        <div class="col-md-2">
            {{ form_row(form.sexe_p2) }}
        </div>
    </div>

    <div class="row bd-callout bd-callout-warning">
        <div class="col-md-5">
             {{ form_row(form.adresse_p2) }}
        </div>
        <div class="col-md-3">
             {{ form_row(form.situation_Familiale) }}
        </div>

    </div>
    <div class="wel ml-8 border-2">
        <h3>Eleves</h3>
        <ul class="eleves" id="eleves_list" data-prototype="{{ form_widget(form.eleves.vars.prototype)|e('html_attr') }}">

        {% for eleve in form.eleves %}
            <div class="border border-primary ml-4 p-3 rounded">
                <h3>Eléve (enfant): {{ loop.index }}</h3>
                <div class="row">
                    <div class="col-md-3">
                      <li>  {{ form_row(eleve.name) }}</li>
                    </div>
                    <div class="col-md-3">
                        <li>  {{ form_row(eleve.prenom) }}
                    </div>
                    <div class="col-md-5">
                        <li>    {{ form_row(eleve.dateNaissance) }}</li>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <li>  {{ form_row(eleve.sexe) }}</li>
                    </div>
                    <div class="col-md-3">
                        <li>   {{ form_row(eleve.classeroom) }}</li>
                    </div>
                </div>


                <div class="row d-none">
                    <div class="col-md-3 d-none">
                        {#                        {{ form_row(eleve.telephone) }}#}

                        {#                        {{ form_row(eleve.email) }}#}

                        {#                        {{ form_row(eleve.parent_p1_p2) }}#}
                    </div>
                </div>
            </div>
        {% endfor %}
        </ul>

        <button type="button" class="btn btn-info add_eleve_link">Add a eleve</button>
</div>

{{ form_rest(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/parent_pere_mere/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ParentPereMere{% endblock %}

{% block body %}
    <h1>Edit ParentPereMere</h1>

    {{ include('parent_pere_mere/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('parent_pere_mere_index') }}">back to list</a>

    {{ include('parent_pere_mere/_delete_form.html.twig') }}
{% endblock %}

templates/parent_pere_mere/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ParentPereMere index{% endblock %}

{% block body %}
    <h1>ParentPereMere index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name_p1</th>
                <th>Prenom_p1</th>
                <th>Email_p1</th>
                <th>Telephone_p1</th>
                <th>Name_p2</th>
                <th>Prenom_p2</th>
                <th>Email_p2</th>
                <th>Telephone_p2</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for parent_pere_mere in parent_pere_meres %}
            <tr>
                <td>{{ parent_pere_mere.id }}</td>
                <td>{{ parent_pere_mere.nameP1 }}</td>
                <td>{{ parent_pere_mere.prenomP1 }}</td>
                <td>{{ parent_pere_mere.emailP1 }}</td>
                <td>{{ parent_pere_mere.telephoneP1 }}</td>
                <td>{{ parent_pere_mere.nameP2 }}</td>
                <td>{{ parent_pere_mere.prenomP2 }}</td>
                <td>{{ parent_pere_mere.emailP2 }}</td>
                <td>{{ parent_pere_mere.telephoneP2 }}</td>
                <td>
                    <a href="{{ path('parent_pere_mere_show', {'id': parent_pere_mere.id}) }}" class="btn btn-info">show</a>
                    <a href="{{ path('parent_pere_mere_edit', {'id': parent_pere_mere.id}) }}" class="btn btn-success">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('parent_pere_mere_new') }}" class="btn btn-primary">Create new</a>
{% endblock %}

templates/parent_pere_mere/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ParentPereMere{% endblock %}

{% block body %}
    <h1>Create new ParentPereMere</h1>

    {{ include('parent_pere_mere/_form.html.twig') }}

    <a href="{{ path('parent_pere_mere_index') }}" class="btn btn-dark">back to list</a>
{% endblock %}

templates/parent_pere_mere/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ParentPereMere{% endblock %}

{% block body %}
    <h1>ParentPereMere</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ parent_pere_mere.id }}</td>
            </tr>
            <tr>
                <th>Name_p1</th>
                <td>{{ parent_pere_mere.nameP1 }}</td>
            </tr>
            <tr>
                <th>Prenom_p1</th>
                <td>{{ parent_pere_mere.prenomP1 }}</td>
            </tr>
            <tr>
                <th>Email_p1</th>
                <td>{{ parent_pere_mere.emailP1 }}</td>
            </tr>
            <tr>
                <th>Telephone_p1</th>
                <td>{{ parent_pere_mere.telephoneP1 }}</td>
            </tr>
            <tr>
                <th>Name_p2</th>
                <td>{{ parent_pere_mere.nameP2 }}</td>
            </tr>
            <tr>
                <th>Prenom_p2</th>
                <td>{{ parent_pere_mere.prenomP2 }}</td>
            </tr>
            <tr>
                <th>Email_p2</th>
                <td>{{ parent_pere_mere.emailP2 }}</td>
            </tr>
            <tr>
                <th>Telephone_p2</th>
                <td>{{ parent_pere_mere.telephoneP2 }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('parent_pere_mere_index') }}">back to list</a>

    <a href="{{ path('parent_pere_mere_edit', {'id': parent_pere_mere.id}) }}">edit</a>

    {{ include('parent_pere_mere/_delete_form.html.twig') }}
{% endblock %}